CREATE DATABASE HOSPITAL_MANAGEMENT;
USE HOSPITAL_MANAGEMENT;
CREATE TABLE PATIENT (
    PATIENT_ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(15)
);
CREATE TABLE DOCTOR (
    DOCTOR_ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    SPECIALIZATION VARCHAR(255),
    EXPERIENCE INT
);
CREATE TABLE RECEPTION (
    APPOINTMENT_ID INT PRIMARY KEY,
    PATIENT_ID INT,
    DOCTOR_ID INT,
    WAITING_TIME TIME,  
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)
);
