create database DATABASE_NAME;
DROP database DATABASE_NAME;
USE DATABASE_NAME;
CREATE TABLE TABLE_NAME(
  COLUMN1 DataType,
  COLUMN1 DataType,
  COLUMN1 DataType
); 
INSERT INTO DATABASE_NAME(COLUMNS...) VALUES
(VAL1,VAL2,VAL3...);
SELECT COLOMN_NAME FORM DATABASE_NAME;
SHOW DATABASES;
SHOW TABLES;
